set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Chiel92/vim-autoformat'
call vundle#end()

filetype plugin indent on

let g:formatterpath=['/usr/bin']
autocmd BufWritePre,BufReadPost *.h,*.hpp,*.c,*.cpp : Autoformat
 
set background=dark
syntax on

set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set smarttab

set hlsearch
set incsearch
set ignorecase
set smartcase

set noswapfile

set number

"set spell spelllang=en_us

inoremap jk <ESC>
let mapleader = ' '
nnoremap <leader>s : set spell!
