set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Chiel92/vim-autoformat'
Plugin 'jremmen/vim-ripgrep'
call vundle#end()

filetype plugin indent on

"let g:formatterpath=['/usr/bin']
"autocmd BufWritePre,BufReadPost *.h,*.hpp,*.c,*.cpp : Autoformat
 
set background=dark
syntax on

set expandtab

set smartindent

set hlsearch
set incsearch
set ignorecase
set smartcase

set wildmenu

set nobackup
set noswapfile

set number

set colorcolumn=80

set laststatus=2

inoremap jk <ESC>
let mapleader = ' '
nnoremap <leader>s : set spell! " toggle spelling highlighting
nnoremap <leader>n : noh<CR>    " turn off highlighting for search results
nnoremap <leader>f : Rg <C-R><C-W><CR> " Rg for the token under the cursor

set path+=./**
set makeprg=build
